version: 2
jobs:
  build:
    environment:
      - USER: scholzj
    docker:
      - image: scholzj/circleci-centos-java:latest
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Build code
          command: make build
      - run:
          name: Build Docker images
          command: make docker_build
      - deploy:
          name: Login to Docker Hub
          command: docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      - deploy:
          name: Push to Docker hub
          command: make docker_push
workflows:
  version: 2
  build-workflow:
    jobs:
      - build:
            context: org-global